baseURL = "https://home-5006704708.app-ionos.space/"
defaultContentLanguage = "de"
title = "Pflegeteam Braunschweig"
theme = "pflege"

buildDrafts = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5


[params]
  ogimage = "/img/og_image.png"
  sitename = "Example Site Name"
  description = "Ambulante Pflege in Braunschweig."


[languages]
  [languages.de]
    languageName = "German"
    languageCode = "de-de"
    weight = 1
